import ts, { SyntaxKind } from "typescript"
import { UsageDomain } from "tsutils"

import { ErrorName, addError } from "../errors"
import { ParseNodeType, ParseState, combine, parseNode } from "../parse_node"
import { Test } from "../tests/test"

import { LibraryFunctions, LibraryFunctionName } from "./library_functions"
import { preRegisterImportAliases } from "./parse_import_declaration"
import { registerNestedFunctionBindings } from "./parse_function_declaration"

/**
 * The class_name and extends statements *must* come first in the file, so we
 * preprocess the class to find them prior to our normal pass.
 */
const getClassDeclarationHeader = (
  node: ts.ClassDeclaration | ts.ClassExpression,
  props: ParseState
) => {
  // TODO: Can be moved into parse_class_declaration i think

  let extendsFrom = ""

  if (node.heritageClauses) {
    // Only `extends` may be emitted; `implements` clauses reference TS
    // interfaces, which do not exist in GDScript.
    const extendsClause = node.heritageClauses.find(
      (clause) => clause.token === SyntaxKind.ExtendsKeyword
    )
    const type = extendsClause?.types[0]

    extendsFrom = type?.getText() ?? ""

    // JS Error has no GDScript counterpart; Error subclasses extend the
    // shim script through its resource path.
    if (extendsFrom === "Error") {
      extendsFrom = '"res://_ts_shims/ts_error.gd"'
    }
  }

  const isTool = !!node.decorators?.find(
    (dec) => dec.expression.getText() === "tool"
  )

  return `${isTool ? "@tool\n" : ""}${
    extendsFrom ? `extends ${extendsFrom}` : ""
  }
${props.isAutoload ? "" : `class_name ${node.name?.getText()}\n`}`
}

export const getFileHeader = (): string => {
  return `# This file has been autogenerated by ts2gd. DO NOT EDIT!\n\n`
}

export const parseSourceFile = (
  node: ts.SourceFile,
  props: ParseState
): ParseNodeType => {
  const { statements } = node
  const sourceInfo = props.project
    .sourceFiles()
    .find((file) => file.fsPath === node.fileName)

  // props.usages = utils.collectVariableUsage(node)
  props.isAutoload = sourceInfo?.isAutoload() ?? false

  const allClasses = statements.filter(
    (statement) =>
      statement.kind === SyntaxKind.ClassDeclaration &&
      // skip class type declarations
      (statement.modifiers ?? []).filter((m) => m.getText() === "declare")
        .length === 0
  ) as ts.ClassDeclaration[]

  if (allClasses.length === 0) {
    addError({
      error: ErrorName.ClassNameNotFound,
      location: node,
      description:
        "Every file must have one class in it, but this file doesn't have any.",
      stack: new Error().stack ?? "",
    })
  }

  /**
   * Class-less modules get a generated class name so static contexts can
   * still form callables targeting the file's own functions.
   */
  const moduleClassName = (() => {
    const rootLength = props.project.paths?.rootPath?.length ?? -1
    const rel =
      rootLength >= 0 && node.fileName.startsWith(props.project.paths.rootPath)
        ? node.fileName.slice(rootLength + 1)
        : node.fileName
    const pascal = rel
      .replace(/\.[^.]+$/, "")
      .split(/[^a-zA-Z0-9]+/)
      .filter((part) => part !== "")
      .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
      .join("")

    let hash = 0

    for (let i = 0; i < rel.length; i++) {
      hash = (hash * 31 + rel.charCodeAt(i)) >>> 0
    }

    return `__Mod_${pascal}_${hash.toString(36)}`
  })()

  const parsedClassDeclarations: {
    fileName: string
    parsedClass: ParseNodeType
    classDecl: ts.ClassDeclaration | ts.ClassExpression
  }[] = []
  // Helpers are collected by name and emitted exactly once per file, no
  // matter how many classes or module-level statements requested them.
  const hoistedLibraryFunctionNames = new Set<LibraryFunctionName>()
  let hoistedEnumImports = ""
  let hoistedArrowFunctions = ""

  /**
   * These are almost always an error - it's invalid to write let x = 5 outside of
   * a method scope in ts2gd. However, we use them for two reasons.
   *
   * 1. They make test writing a heck of a lot more convenient - no need to wrap
   * everything in a class
   * 2. They are used to declare the autoload global variable.
   */
  let toplevelStatements: ts.Statement[] = []

  const files: { filePath: string; body: string }[] = []

  props.moduleClassName = moduleClassName

  // Register nested (inner) function declarations before parsing so forward
  // references resolve (function declarations hoist in JS).
  registerNestedFunctionBindings(node, props)

  // Reserve import receivers and register imported binding names before any
  // class body is parsed: class members parse first, and their references
  // to imported modules must resolve to the receiver expressions.
  for (const statement of statements) {
    if (statement.kind === SyntaxKind.ImportDeclaration) {
      preRegisterImportAliases(statement as ts.ImportDeclaration, props)
    }
  }

  for (const statement of statements) {
    if (
      statement.kind !== SyntaxKind.ClassDeclaration &&
      statement.kind !== SyntaxKind.ClassExpression
    ) {
      toplevelStatements.push(statement)

      continue
    }

    const parsedStatement = parseNode(statement, props)

    if (!statement.modifiers?.map((m) => m.getText()).includes("declare")) {
      // TODO: Push this logic into class declaration and expression classes

      const classDecl = statement as ts.ClassDeclaration | ts.ClassExpression
      const className = classDecl.name?.text

      if (!className) {
        addError({
          description: "Anonymous classes are not supported",
          error: ErrorName.ClassCannotBeAnonymous,
          location: classDecl,
          stack: new Error().stack ?? "",
        })

        continue
      }

      parsedClassDeclarations.push({
        fileName:
          props.sourceFileAsset.gdContainingDirectory + className + ".gd",
        parsedClass: parsedStatement,
        classDecl,
      })
    }

    for (const lf of parsedStatement.hoistedLibraryFunctions ?? []) {
      hoistedLibraryFunctionNames.add(lf)
    }

    for (const af of parsedStatement.hoistedArrowFunctions ?? []) {
      hoistedArrowFunctions += af.content + "\n"
    }

    for (const fi of parsedStatement.files ?? []) {
      files.push(fi)
    }
  }

  /**
   * Executable statements cannot live in a GDScript class body ("Unexpected
   * 'for' in class body"). They compile into a static init function that
   * Godot calls when the class loads, mirroring JS module-evaluation
   * semantics. Declarations stay where they were.
   */
  const executableStatementKinds = new Set<number>([
    SyntaxKind.IfStatement,
    SyntaxKind.ForStatement,
    SyntaxKind.ForOfStatement,
    SyntaxKind.ForInStatement,
    SyntaxKind.WhileStatement,
    SyntaxKind.DoStatement,
    SyntaxKind.SwitchStatement,
    SyntaxKind.ExpressionStatement,
    SyntaxKind.LabeledStatement,
    SyntaxKind.TryStatement,
    SyntaxKind.ThrowStatement,
    SyntaxKind.DebuggerStatement,
    SyntaxKind.ReturnStatement,
  ])

  const moduleDeclarations = toplevelStatements.filter(
    (statement) => !executableStatementKinds.has(statement.kind)
  )
  const moduleInitStatements = toplevelStatements.filter((statement) =>
    executableStatementKinds.has(statement.kind)
  )

  // Toplevel code is static: callables built inside it (and module-level
  // function values) must target the file's class rather than an instance.
  // For class-ful files that is the declared class itself, since module
  // declarations are emitted at file level next to its members.
  const enclosingClassName = allClasses[0]?.name?.getText() ?? moduleClassName
  const previousModuleClassName = props.moduleClassName
  props.moduleClassName = enclosingClassName

  const previousStaticContext = props.inStaticContext
  props.inStaticContext = true

  const codegenToplevelDeclarations =
    moduleDeclarations.length > 0
      ? combine({
          nodes: moduleDeclarations,
          parent: moduleDeclarations[0].parent,
          props,
          parsedStrings: (...strs) => strs.join("\n"),
        })
      : undefined

  let codegenModuleInit: ParseNodeType | undefined

  if (moduleInitStatements.some((s) => s.kind !== SyntaxKind.EmptyStatement)) {
    codegenModuleInit = combine({
      nodes: moduleInitStatements,
      parent: moduleInitStatements[0].parent,
      props,
      parsedStrings: (...strs) => {
        const body = strs
          .filter((s) => s.trim() !== "")
          .map((s) =>
            s
              .split("\n")
              .map((line) => (line.trim() === "" ? line : "  " + line))
              .join("\n")
          )
          .join("\n")

        return `static func _static_init():${body ? "\n" + body : "\n  pass"}`
      },
    })
  }

  props.inStaticContext = previousStaticContext

  props.moduleClassName = previousModuleClassName

  for (const lf of codegenToplevelDeclarations?.hoistedLibraryFunctions ?? []) {
    hoistedLibraryFunctionNames.add(lf)
  }

  for (const af of codegenToplevelDeclarations?.hoistedArrowFunctions ?? []) {
    hoistedArrowFunctions += af.content + "\n"
  }

  for (const fi of codegenToplevelDeclarations?.files ?? []) {
    files.push(fi)
  }

  for (const lf of codegenModuleInit?.hoistedLibraryFunctions ?? []) {
    hoistedLibraryFunctionNames.add(lf)
  }

  for (const af of codegenModuleInit?.hoistedArrowFunctions ?? []) {
    hoistedArrowFunctions += af.content + "\n"
  }

  for (const fi of codegenModuleInit?.files ?? []) {
    files.push(fi)
  }

  // The assert helper's template checks its condition through the truthiness
  // helper, so emitting one must pull in the other regardless of whether any
  // user code requested a truthiness check of its own.
  if (hoistedLibraryFunctionNames.has("ts_assert")) {
    hoistedLibraryFunctionNames.add("ts_truthy")
  }

  const hoistedLibraryFunctionDefinitions = [...hoistedLibraryFunctionNames]
    .map(
      (lf) =>
        LibraryFunctions[lf].definition("__" + LibraryFunctions[lf].name) + "\n"
    )
    .join("")

  /**
   * Names used as runtime values anywhere in the source file, by text. The
   * usage map is keyed by identifier nodes, so this flattens it once for
   * lookup by the per-file sibling receivers below.
   */
  const valueUsedNames = new Set<string>()

  for (const [id, info] of props.usages.entries()) {
    if (
      id.kind === SyntaxKind.Identifier &&
      info.uses.some((use) => use.domain & UsageDomain.Value)
    ) {
      valueUsedNames.add(id.text)
    }
  }

  /**
   * A module with several top-level classes compiles each class into its own
   * script, so sibling classes stop being visible by name. Value-used
   * siblings get a load() receiver in every sibling file (except the class's
   * own file, where the class name already resolves), mirroring how
   * cross-module class imports are emitted.
   */
  const siblingReceiversFor = (selfName: string): string => {
    if (parsedClassDeclarations.length < 2) {
      return ""
    }

    const dir = props.sourceFileAsset?.gdContainingDirectory ?? ""
    const toRes = (fsPath: string): string =>
      props.project?.paths?.fsPathToResPath
        ? props.project.paths.fsPathToResPath(fsPath)
        : "res://" + fsPath.replace(/^\/+/, "")

    const lines = parsedClassDeclarations
      .map((pc) => pc.classDecl.name?.text)
      .filter(
        (name): name is string =>
          !!name && name !== selfName && valueUsedNames.has(name)
      )
      .map(
        (name) => `static var ${name} = load("${toRes(dir + name + ".gd")}")\n`
      )

    return lines.join("")
  }

  for (const { fileName, parsedClass, classDecl } of parsedClassDeclarations) {
    files.push({
      filePath: fileName,
      body: `
${getFileHeader()}
${getClassDeclarationHeader(classDecl, props)}    
${siblingReceiversFor(classDecl.name?.text ?? "")}
${hoistedEnumImports}
${hoistedLibraryFunctionDefinitions}
${hoistedArrowFunctions}
${codegenToplevelDeclarations?.content ?? ""}
${codegenModuleInit?.content ?? ""}
${parsedClass.content}`,
    })
  }

  if (parsedClassDeclarations.length === 0) {
    // Class-less module: emit its functions as static members of a
    // generated named class.

    files.push({
      filePath: props.sourceFileAsset.gdPath,
      body: `
${getFileHeader()}
class_name ${moduleClassName}
${hoistedEnumImports}
${hoistedLibraryFunctionDefinitions}
${hoistedArrowFunctions}
${codegenToplevelDeclarations?.content ?? ""}
${codegenModuleInit?.content ?? ""}`,
    })
  }

  return {
    files,
    content: "",
  }
}

export const testToolAnnotation: Test = {
  ts: `
@tool
export class Test {
}
  `,
  expected: `
@tool
class_name Test
`,
}

export const testTwoClasses: Test = {
  ts: `
export class Test1 { }
export class Test2 { }
  `,
  expected: {
    type: "multiple-files",
    files: [
      {
        fileName: "/Users/johnfn/MyGame/compiled/Test1.gd",
        expected: `class_name Test1`,
      },
      {
        fileName: "/Users/johnfn/MyGame/compiled/Test2.gd",
        expected: `class_name Test2`,
      },
    ],
  },
}

export const testSiblingClassReceiverAcrossSplitFiles: Test = {
  ts: `
export class Alpha {
  build() {
    return new Beta()
  }
}

export class Beta {
  value() {
    return 7
  }
}
  `,
  expected: {
    type: "multiple-files",
    files: [
      {
        fileName: "/Users/johnfn/MyGame/compiled/Alpha.gd",
        expected: `class_name Alpha
static var Beta = load("res://Users/johnfn/MyGame/compiled/Beta.gd")
func build():
  return Beta.new()`,
      },
      {
        fileName: "/Users/johnfn/MyGame/compiled/Beta.gd",
        expected: `class_name Beta
func value():
  return 7`,
      },
    ],
  },
}

export const testImplementsClauseIgnored: Test = {
  ts: `
interface Shape {
  area(): int
}

export class Circle implements Shape {
  area(): int {
    return 1
  }
}
  `,
  expected: {
    type: "multiple-files",
    files: [
      {
        fileName: "/Users/johnfn/MyGame/compiled/Circle.gd",
        expected: `class_name Circle
func area():
  return 1`,
      },
    ],
  },
}

export const testDebuggerStatement: Test = {
  ts: `
export class Test {
  go() {
    debugger
  }
}
  `,
  expected: `
class_name Test
func go():
  breakpoint
`,
}

export const testHelperEmittedOnceAcrossClassAndModuleScope: Test = {
  ts: `
const cues = new Set<string>()
export class Foo {
  private owners = new Set<string>()
}
  `,
  expected: `
class_name Foo
${LibraryFunctions.ts_new_set.definition("__ts_new_set")}
static var _cues = __ts_new_set()
var owners = __ts_new_set()
  `,
}

export const testModuleStatementsLandInStaticInit: Test = {
  ts: `
const thresholds = [4, 8]
for (const t of thresholds) {
  void t
}
let guard = 0
while (guard < 2) {
  guard += 1
}
  `,
  expected: `
class_name __Mod_Test_4064or
static var thresholds = [4, 8]
static var guard: int = 0

static func _static_init():
  for t in thresholds:
    null
  while guard < 2:
    guard += 1
  `,
}

export const testModuleInitCallableTargetsModuleClass: Test = {
  ts: `
function warn(kind: string) {
  print(kind)
}
[1, 2].forEach((n) => warn(n === 1 ? "one" : "many"))
  `,
  expected: `
class_name __Mod_Test_4064or
${LibraryFunctions.ts_array_for_each.definition("__ts_array_for_each")}
${LibraryFunctions.ts_call_fn.definition("__ts_call_fn")}
${LibraryFunctions.ts_truthy.definition("__ts_truthy")}
static func __gen(n, captures):
  return warn("one" if n == 1 else "many")
static func warn(kind: String):
  print(kind)

static func _static_init():
  __ts_array_for_each([1, 2], [Callable(__Mod_Test_4064or, "__gen"), {}])
  `,
}
