import ts from "typescript"

import { ParseNodeType, ParseState, combine } from "../parse_node"
import { Test } from "../tests/test"

import { resolveLabeledJump } from "./label_utils"

export const parseBreakStatement = (
  node: ts.BreakStatement,
  props: ParseState
): ParseNodeType => {
  if (node.label) {
    const resolved = resolveLabeledJump(
      props,
      node.label.text,
      false,
      props.mostRecentControlStructureIsSwitch
    )

    if (resolved.matched) {
      return combine({
        parent: node,
        nodes: [],
        props,
        parsedStrings: () => resolved.lines.join("\n") + "\n",
      })
    }
  }

  if (props.mostRecentControlStructureIsSwitch) {
    return combine({
      parent: node,
      nodes: [],
      props,
      parsedStrings: () => "",
    })
  } else {
    return combine({
      parent: node,
      nodes: [],
      props,
      parsedStrings: () => `
${props.mostRecentForStatement?.incrementor ?? ""}
break
`,
    })
  }
}

export const testBreak1: Test = {
  ts: `
for (let x = 0; x < 10; x++) {
  break;
  print(x);
}
  `,
  expected: `
# This file has been autogenerated by ts2gd. DO NOT EDIT!


class_name __Mod_Test_4064or




static func _static_init():
  static var x: int = 0

  while x < 10:
    x += 1
    break
  
    print(x)
  

    x += 1
`,
}

export const testBreak2: Test = {
  ts: `
for (let x: int = 0; x < 10; x++) {
  if (x == (0 as int)) break;
  print(x);
}
  `,
  expected: `
# This file has been autogenerated by ts2gd. DO NOT EDIT!


class_name __Mod_Test_4064or




static func _static_init():
  static var x: int = 0

  while x < 10:
    if x == 0:
      x += 1
      break
  
    print(x)
  

    x += 1
`,
}
