import ts, { SyntaxKind } from "typescript"

import { ErrorName, addError } from "../errors"
import { ParseNodeType, ParseState, combine, parseNode } from "../parse_node"
import { Test } from "../tests/test"

import { LibraryFunctions, LibraryFunctionName } from "./library_functions"
import { registerNestedFunctionBindings } from "./parse_function_declaration"

/**
 * The class_name and extends statements *must* come first in the file, so we
 * preprocess the class to find them prior to our normal pass.
 */
const getClassDeclarationHeader = (
  node: ts.ClassDeclaration | ts.ClassExpression,
  props: ParseState
) => {
  // TODO: Can be moved into parse_class_declaration i think

  let extendsFrom = ""

  if (node.heritageClauses) {
    // Only `extends` may be emitted; `implements` clauses reference TS
    // interfaces, which do not exist in GDScript.
    const extendsClause = node.heritageClauses.find(
      (clause) => clause.token === SyntaxKind.ExtendsKeyword
    )
    const type = extendsClause?.types[0]

    extendsFrom = type?.getText() ?? ""
  }

  const isTool = !!node.decorators?.find(
    (dec) => dec.expression.getText() === "tool"
  )

  return `${isTool ? "@tool\n" : ""}${
    extendsFrom ? `extends ${extendsFrom}` : ""
  }
${props.isAutoload ? "" : `class_name ${node.name?.getText()}\n`}`
}

export const getFileHeader = (): string => {
  return `# This file has been autogenerated by ts2gd. DO NOT EDIT!\n\n`
}

export const parseSourceFile = (
  node: ts.SourceFile,
  props: ParseState
): ParseNodeType => {
  const { statements } = node
  const sourceInfo = props.project
    .sourceFiles()
    .find((file) => file.fsPath === node.fileName)

  // props.usages = utils.collectVariableUsage(node)
  props.isAutoload = sourceInfo?.isAutoload() ?? false

  const allClasses = statements.filter(
    (statement) =>
      statement.kind === SyntaxKind.ClassDeclaration &&
      // skip class type declarations
      (statement.modifiers ?? []).filter((m) => m.getText() === "declare")
        .length === 0
  ) as ts.ClassDeclaration[]

  if (allClasses.length === 0) {
    addError({
      error: ErrorName.ClassNameNotFound,
      location: node,
      description:
        "Every file must have one class in it, but this file doesn't have any.",
      stack: new Error().stack ?? "",
    })
  }

  /**
   * Class-less modules get a generated class name so static contexts can
   * still form callables targeting the file's own functions.
   */
  const moduleClassName = (() => {
    const rootLength = props.project.paths?.rootPath?.length ?? -1
    const rel =
      rootLength >= 0 && node.fileName.startsWith(props.project.paths.rootPath)
        ? node.fileName.slice(rootLength + 1)
        : node.fileName
    const pascal = rel
      .replace(/\.[^.]+$/, "")
      .split(/[^a-zA-Z0-9]+/)
      .filter((part) => part !== "")
      .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
      .join("")

    let hash = 0

    for (let i = 0; i < rel.length; i++) {
      hash = (hash * 31 + rel.charCodeAt(i)) >>> 0
    }

    return `__Mod_${pascal}_${hash.toString(36)}`
  })()

  const parsedClassDeclarations: {
    fileName: string
    parsedClass: ParseNodeType
    classDecl: ts.ClassDeclaration | ts.ClassExpression
  }[] = []
  // Helpers are collected by name and emitted exactly once per file, no
  // matter how many classes or module-level statements requested them.
  const hoistedLibraryFunctionNames = new Set<LibraryFunctionName>()
  let hoistedEnumImports = ""
  let hoistedArrowFunctions = ""

  /**
   * These are almost always an error - it's invalid to write let x = 5 outside of
   * a method scope in ts2gd. However, we use them for two reasons.
   *
   * 1. They make test writing a heck of a lot more convenient - no need to wrap
   * everything in a class
   * 2. They are used to declare the autoload global variable.
   */
  let toplevelStatements: ts.Statement[] = []

  const files: { filePath: string; body: string }[] = []

  props.moduleClassName = moduleClassName

  // Register nested (inner) function declarations before parsing so forward
  // references resolve (function declarations hoist in JS).
  registerNestedFunctionBindings(node, props)

  for (const statement of statements) {
    if (
      statement.kind !== SyntaxKind.ClassDeclaration &&
      statement.kind !== SyntaxKind.ClassExpression
    ) {
      toplevelStatements.push(statement)

      continue
    }

    const parsedStatement = parseNode(statement, props)

    if (!statement.modifiers?.map((m) => m.getText()).includes("declare")) {
      // TODO: Push this logic into class declaration and expression classes

      const classDecl = statement as ts.ClassDeclaration | ts.ClassExpression
      const className = classDecl.name?.text

      if (!className) {
        addError({
          description: "Anonymous classes are not supported",
          error: ErrorName.ClassCannotBeAnonymous,
          location: classDecl,
          stack: new Error().stack ?? "",
        })

        continue
      }

      parsedClassDeclarations.push({
        fileName:
          props.sourceFileAsset.gdContainingDirectory + className + ".gd",
        parsedClass: parsedStatement,
        classDecl,
      })
    }

    for (const lf of parsedStatement.hoistedLibraryFunctions ?? []) {
      hoistedLibraryFunctionNames.add(lf)
    }

    for (const af of parsedStatement.hoistedArrowFunctions ?? []) {
      hoistedArrowFunctions += af.content + "\n"
    }

    for (const fi of parsedStatement.files ?? []) {
      files.push(fi)
    }
  }

  const codegenToplevelStatements =
    toplevelStatements.length > 0
      ? combine({
          nodes: toplevelStatements,
          parent: toplevelStatements[0].parent,
          props,
          parsedStrings: (...strs) => strs.join("\n"),
        })
      : undefined

  for (const lf of codegenToplevelStatements?.hoistedLibraryFunctions ?? []) {
    hoistedLibraryFunctionNames.add(lf)
  }

  for (const af of codegenToplevelStatements?.hoistedArrowFunctions ?? []) {
    hoistedArrowFunctions += af.content + "\n"
  }

  for (const fi of codegenToplevelStatements?.files ?? []) {
    files.push(fi)
  }

  const hoistedLibraryFunctionDefinitions = [...hoistedLibraryFunctionNames]
    .map(
      (lf) =>
        LibraryFunctions[lf].definition("__" + LibraryFunctions[lf].name) + "\n"
    )
    .join("")

  for (const { fileName, parsedClass, classDecl } of parsedClassDeclarations) {
    files.push({
      filePath: fileName,
      body: `
${getFileHeader()}
${getClassDeclarationHeader(classDecl, props)}    
${hoistedEnumImports}
${hoistedLibraryFunctionDefinitions}
${hoistedArrowFunctions}
${codegenToplevelStatements?.content ?? ""}
${parsedClass.content}`,
    })
  }

  if (parsedClassDeclarations.length === 0) {
    // Class-less module: emit its functions as static members of a
    // generated named class.

    files.push({
      filePath: props.sourceFileAsset.gdPath,
      body: `
${getFileHeader()}
class_name ${moduleClassName}
${hoistedEnumImports}
${hoistedLibraryFunctionDefinitions}
${hoistedArrowFunctions}
${codegenToplevelStatements?.content ?? ""}`,
    })
  }

  return {
    files,
    content: "",
  }
}

export const testToolAnnotation: Test = {
  ts: `
@tool
export class Test {
}
  `,
  expected: `
@tool
class_name Test
`,
}

export const testTwoClasses: Test = {
  ts: `
export class Test1 { }
export class Test2 { }
  `,
  expected: {
    type: "multiple-files",
    files: [
      {
        fileName: "/Users/johnfn/MyGame/compiled/Test1.gd",
        expected: `class_name Test1`,
      },
      {
        fileName: "/Users/johnfn/MyGame/compiled/Test2.gd",
        expected: `class_name Test2`,
      },
    ],
  },
}

export const testImplementsClauseIgnored: Test = {
  ts: `
interface Shape {
  area(): int
}

export class Circle implements Shape {
  area(): int {
    return 1
  }
}
  `,
  expected: {
    type: "multiple-files",
    files: [
      {
        fileName: "/Users/johnfn/MyGame/compiled/Circle.gd",
        expected: `class_name Circle
func area():
  return 1`,
      },
    ],
  },
}

export const testDebuggerStatement: Test = {
  ts: `
export class Test {
  go() {
    debugger
  }
}
  `,
  expected: `
class_name Test
func go():
  breakpoint
`,
}

export const testHelperEmittedOnceAcrossClassAndModuleScope: Test = {
  ts: `
const cues = new Set<string>()
export class Foo {
  private owners = new Set<string>()
}
  `,
  expected: `
class_name Foo
${LibraryFunctions.ts_new_set.definition("__ts_new_set")}
static var _cues = __ts_new_set()
var owners = __ts_new_set()
  `,
}
