import ts from "typescript"

import {
  ExtraLine,
  ExtraLineType,
  ParseState,
  combine,
  ParseNodeType,
} from "../parse_node"
import { Test } from "../tests/test"
import { syntaxKindToString } from "../ts_utils"
const { SyntaxKind } = ts

export const parsePostfixUnaryExpression = (
  node: ts.PostfixUnaryExpression,
  props: ParseState
): ParseNodeType => {
  let newIncrements: ExtraLine | null = null

  const result = combine({
    parent: node,
    nodes: node.operand,
    props,
    parsedStrings: (operand) => {
      switch (node.operator) {
        case SyntaxKind.PlusPlusToken:
          newIncrements = {
            type: "after",
            line: `${operand} += 1`,
            lineType: ExtraLineType.Increment,
          }
          break

        case SyntaxKind.MinusMinusToken:
          newIncrements = {
            type: "after",
            line: `${operand} -= 1`,
            lineType: ExtraLineType.Decrement,
          }
          break
      }

      if (node.parent.kind === SyntaxKind.ExpressionStatement) {
        return ""
      } else {
        return `${operand}`
      }
    },
  })

  result.extraLines = [
    ...(newIncrements ? [newIncrements] : []),
    ...(result.extraLines ?? []),
  ]

  return result
}

export const testBasicInc: Test = {
  ts: `
var x = 1
x++
  `,
  expected: `
# This file has been autogenerated by ts2gd. DO NOT EDIT!


class_name __Mod_Test_4064or



static var x: int = 1

static func _static_init():

  x += 1
`,
}

export const testBasicInc2: Test = {
  ts: `
var x = 1
if (x++) {
  print(x)
} 
  `,
  expected: `
# This file has been autogenerated by ts2gd. DO NOT EDIT!


class_name __Mod_Test_4064or



static var x: int = 1

static func _static_init():
  if x:
    x += 1
    print(x)
  


  else:
    x += 1
`,
}
