import ts, { SyntaxKind } from "typescript"

import { ParseState, combine, ParseNodeType } from "../parse_node"
import { Test } from "../tests/test"

import {
  adoptPendingLabel,
  labelFlagDeclarations,
  labelFlagResets,
  labelPropagationChecks,
  unlabeledEntry,
} from "./label_utils"

const loopLabelParts = (props: ParseState) => {
  const incoming = props.labelStack ?? []
  const entry = props.pendingLabel
    ? adoptPendingLabel(props)
    : unlabeledEntry("")
  const bodyProps = {
    ...props,
    pendingLabel: undefined,
    labelStack: [...incoming, entry],
  }

  return {
    bodyProps,
    declBlock:
      labelFlagDeclarations(entry).length > 0
        ? labelFlagDeclarations(entry).join("\n") + "\n"
        : "",
    resetBlock:
      labelFlagResets(entry).length > 0
        ? labelFlagResets(entry)
            .map((l) => `  ${l}`)
            .join("\n") + "\n"
        : "",
    checkBlock:
      labelPropagationChecks(incoming).length > 0
        ? labelPropagationChecks(incoming).join("\n") + "\n"
        : "",
  }
}

export const parseForInStatement = (
  node: ts.ForInStatement,
  props: ParseState
): ParseNodeType => {
  let result: ParseNodeType

  props.scope.enterScope()

  if (node.initializer.kind === SyntaxKind.VariableDeclarationList) {
    const vdl = node.initializer as ts.VariableDeclarationList

    if (vdl.declarations.length > 1 || vdl.declarations.length === 0) {
      throw new Error("non-1 length of declarations in for...in")
    }

    const { bodyProps, declBlock, resetBlock, checkBlock } =
      loopLabelParts(props)

    result = combine({
      parent: node,
      nodes: [vdl.declarations[0].name, node.expression, node.statement],
      props: bodyProps,
      addIndent: true,
      parsedStrings: (name, expr, statement) => `
${declBlock}for ${name} in ${expr}:
${resetBlock}  ${statement}
${checkBlock}`,
    })
  } else {
    const initExpr = node.initializer as ts.Expression

    const { bodyProps, declBlock, resetBlock, checkBlock } =
      loopLabelParts(props)

    result = combine({
      parent: node,
      nodes: [initExpr, node.expression, node.statement],
      props: bodyProps,
      addIndent: true,
      parsedStrings: (initExpr, expr, statement) => `
${declBlock}for ${initExpr} in ${expr}:
${resetBlock}  ${statement}
${checkBlock}`,
    })
  }

  props.scope.leaveScope()

  return result
}

export const testForIn1: Test = {
  ts: `
for (let x in []);
  `,
  expected: `
# This file has been autogenerated by ts2gd. DO NOT EDIT!


class_name __Mod_Test_4064or




static func _static_init():
  for x in []:
    pass
`,
}

export const testForIn2: Test = {
  ts: `
let x: never;
for (x in []);
  `,
  expected: `
# This file has been autogenerated by ts2gd. DO NOT EDIT!


class_name __Mod_Test_4064or



static var x

static func _static_init():
  for x in []:
    pass
`,
}
