import ts from "typescript"

import { ParseNodeType, ParseState, combine } from "../parse_node"
import { Test } from "../tests/test"

export const parseVariableDeclarationList = (
  node: ts.VariableDeclarationList,
  props: ParseState
): ParseNodeType => {
  // Satisfies clauses parse as real syntax only on newer TypeScript; on
  // the grammar this project targets, error recovery splits the clause
  // into trailing declaration ghosts whose first identifier spells
  // "satisfies". The recovery never binds initializers, so everything
  // from that declaration onward in the list drops.
  const ghostStart = node.declarations.findIndex(
    (d) =>
      !d.initializer && ts.isIdentifier(d.name) && d.name.text === "satisfies"
  )
  const declarations =
    ghostStart === -1
      ? node.declarations
      : node.declarations.slice(0, ghostStart)

  return combine({
    parent: node,
    nodes: declarations,
    props,
    parsedStrings: (...decls) => decls.join("\n") + "\n",
  })
}

export const testVDL: Test = {
  ts: `
let a = 1, b = 2
print(a)
print(b)
  `,
  expected: `
# This file has been autogenerated by ts2gd. DO NOT EDIT!


class_name __Mod_Test_4064or



static var a: int = 1
static var b: int = 2

static func _static_init():
  print(a)

  print(b)
`,
}

export const testVDL2: Test = {
  ts: `
export class Test extends Area2D {
  constructor() {
    super()
    let x = 1, y = 2;
    this.print(1)
  }
}`,
  expected: `
extends Area2D
class_name Test
func _init():
  var _x: int = 1
  var _y: int = 2
  self.print(1)
`,
}

export const testSatisfiesClauseDropsGhosts: Test = {
  ts: `
export const CUES = {
  0x28: 'swing',
} as const satisfies Record<0x28 | 0x64 | 0x65 | 0x75, SfxCue>;
  `,
  expected: `
# This file has been autogenerated by ts2gd. DO NOT EDIT!


class_name __Mod_Test_4064or



static var _CUES = {
  0x28: "swing",
}
`,
}
