import ts from "typescript"

import { ParseState, combine, ParseNodeType } from "../parse_node"
import { Test } from "../tests/test"

import { getDestructuredNamesAndAccessStrings } from "./parse_variable_declaration"
import {
  adoptPendingLabel,
  labelFlagDeclarations,
  labelFlagResets,
  labelPropagationChecks,
  unlabeledEntry,
} from "./label_utils"
const { SyntaxKind } = ts

const loopLabelParts = (props: ParseState) => {
  const incoming = props.labelStack ?? []
  const entry = props.pendingLabel
    ? adoptPendingLabel(props)
    : unlabeledEntry("")
  const bodyProps = {
    ...props,
    pendingLabel: undefined,
    labelStack: [...incoming, entry],
  }

  return {
    bodyProps,
    declBlock:
      labelFlagDeclarations(entry).length > 0
        ? labelFlagDeclarations(entry).join("\n") + "\n"
        : "",
    resetBlock:
      labelFlagResets(entry).length > 0
        ? labelFlagResets(entry)
            .map((l) => `  ${l}`)
            .join("\n") + "\n"
        : "",
    checkBlock:
      labelPropagationChecks(incoming).length > 0
        ? labelPropagationChecks(incoming).join("\n") + "\n"
        : "",
  }
}

export const parseForOfStatement = (
  node: ts.ForOfStatement,
  props: ParseState
): ParseNodeType => {
  const initializer = node.initializer
  let result: ParseNodeType

  props.scope.enterScope()

  if (initializer.kind === SyntaxKind.VariableDeclarationList) {
    const initializerNode = initializer as ts.VariableDeclarationList

    if (initializerNode.declarations.length > 1) {
      throw new Error("Uh oh! For...of with > 1 declaration")
    }

    const name = initializerNode.declarations[0].name

    if (name.kind === SyntaxKind.Identifier) {
      // Common case - single variable in for... of
      // like for (const x of list)

      // Registering the loop variable lets it mangle when it collides
      // with a live binding (a parameter or enclosing local); GDScript
      // refuses parameters shadowed by loop variables, and body
      // references follow the same registration.
      props.scope.addName(name)

      const { bodyProps, declBlock, resetBlock, checkBlock } =
        loopLabelParts(props)

      result = combine({
        parent: node,
        nodes: [node.expression, node.statement, name],
        props: bodyProps,
        addIndent: true,
        parsedStrings: (expr, statement, name) => `
${declBlock}for ${name} in ${expr}:
${resetBlock}  ${statement}
${checkBlock}`,
      })
    } else {
      // Destructured case
      // like for (const [a, b] of list)

      const destructuredNames = getDestructuredNamesAndAccessStrings(
        initializerNode.declarations[0].name
      )

      for (const { id } of destructuredNames) {
        props.scope.addName(id)
      }

      const genName = props.scope.createUniqueName()

      const { bodyProps, declBlock, resetBlock, checkBlock } =
        loopLabelParts(props)

      result = combine({
        parent: node,
        nodes: [
          node.expression,
          node.statement,
          ...destructuredNames.map((d) => d.id),
        ],
        props: bodyProps,
        addIndent: true,
        parsedStrings: (expr, statement, ...nodes) => `
${declBlock}for ${genName} in ${expr}:
${nodes
  .map(
    (node, i) => `  var ${node} = ${genName}${destructuredNames[i].access}\n`
  )
  .join("")}
${resetBlock}  ${statement}
${checkBlock}`,
      })
    }
  } else {
    const initExpr = initializer as ts.Expression

    const { bodyProps, declBlock, resetBlock, checkBlock } =
      loopLabelParts(props)

    result = combine({
      parent: node,
      nodes: [initExpr, node.expression, node.statement],
      props: bodyProps,
      addIndent: true,
      parsedStrings: (expr, statement) => `
${declBlock}for ${initExpr} in ${expr}:
${resetBlock}  ${statement}
${checkBlock}`,
    })
  }

  props.scope.leaveScope()

  return result
}

export const testBasicForOf: Test = {
  ts: `
for (let x of []) print(1)
  `,
  expected: `
# This file has been autogenerated by ts2gd. DO NOT EDIT!


class_name __Mod_Test_4064or




static func _static_init():
  for x in []:
    print(1)
`,
}

export const testForOfDestructuring: Test = {
  ts: `
for (let [a, b] of [[1, 2]]) print(a, b)
  `,
  expected: `
# This file has been autogenerated by ts2gd. DO NOT EDIT!


class_name __Mod_Test_4064or




static func _static_init():
  for __gen in [[1, 2]]:
    var a = __gen[0]
    var b = __gen[1]

    print(a, b)
`,
}

export const testForOfLabeledContinue: Test = {
  ts: `
const arr = [1, 2]
outer: for (const v of arr) {
  for (const w of arr) {
    if (w == 2) continue outer
    print(v)
  }
}
  `,
  expected: `
# This file has been autogenerated by ts2gd. DO NOT EDIT!


class_name __Mod_Test_4064or



static var arr = [1, 2]

static func _static_init():
  var __ts_continue_outer = false
  var __ts_break_outer = false
  for v in arr:
    __ts_continue_outer = false
    __ts_break_outer = false
    for w in arr:
      if w == 2:
        __ts_continue_outer = true
        break
    
      print(v)
    
  
    if __ts_continue_outer:
      __ts_continue_outer = false
      continue
    if __ts_break_outer:
      break
`,
}

export const testForOfLoopVarCollidingWithParam: Test = {
  ts: `
export function step(state: { hp: number }, victims: { hp: number }[]) {
  for (const state of victims) {
    print(state.hp)
  }
  print(state.hp)
}
  `,
  expected: `
# This file has been autogenerated by ts2gd. DO NOT EDIT!


class_name __Mod_Test_4064or



static func step(state, victims):
  for state1 in victims:
    print(state1.hp)
  
  print(state.hp)
`,
}
