/**
 * Custom code to generate previews. Check [member EditorSettings.filesystem/file_dialog/thumbnail_size] to find a proper size to generate previews at.
 *
 */
declare class EditorResourcePreviewGenerator extends RefCounted {
  /**
   * Custom code to generate previews. Check [member EditorSettings.filesystem/file_dialog/thumbnail_size] to find a proper size to generate previews at.
   *
   */
  new(): EditorResourcePreviewGenerator
  constructor()
  static new(): EditorResourcePreviewGenerator

  /**
   * If this function returns `true`, the generator will call [method _generate] or [method _generate_from_path] for small previews as well.
   *
   * By default, it returns `false`.
   *
   */
  protected _can_generate_small_preview(): boolean

  /**
   * Generate a preview from a given resource with the specified size. This must always be implemented.
   *
   * Returning `null` is an OK way to fail and let another generator take care.
   *
   * Care must be taken because this function is always called from a thread (not the main thread).
   *
   * [param metadata] dictionary can be modified to store file-specific metadata that can be used in [method EditorResourceTooltipPlugin._make_tooltip_for_path] (like image size, sample length etc.).
   *
   */
  protected _generate(
    resource: Resource,
    size: Vector2i,
    metadata: Dictionary<any, any>
  ): Texture2D

  /**
   * Generate a preview directly from a path with the specified size. Implementing this is optional, as default code will load and call [method _generate].
   *
   * Returning `null` is an OK way to fail and let another generator take care.
   *
   * Care must be taken because this function is always called from a thread (not the main thread).
   *
   * [param metadata] dictionary can be modified to store file-specific metadata that can be used in [method EditorResourceTooltipPlugin._make_tooltip_for_path] (like image size, sample length etc.).
   *
   */
  protected _generate_from_path(
    path: string,
    size: Vector2i,
    metadata: Dictionary<any, any>
  ): Texture2D

  /**
   * If this function returns `true`, the generator will automatically generate the small previews from the normal preview texture generated by the methods [method _generate] or [method _generate_from_path].
   *
   * By default, it returns `false`.
   *
   */
  protected _generate_small_preview_automatically(): boolean

  /** Returns [code]true[/code] if your generator supports the resource of type [param type]. */
  protected _handles(type: string): boolean

  /** Call from within [method _generate] to request the rendering server draw to the [param viewport]. */
  request_draw_and_wait(viewport: RID): void

  connect<T extends SignalsOf<EditorResourcePreviewGenerator>>(
    signal: T,
    method: SignalFunction<EditorResourcePreviewGenerator[T]>
  ): number
}
