/**
 * [LightmapGIData] contains baked lightmap and dynamic object probe data for [LightmapGI]. It is replaced every time lightmaps are baked in [LightmapGI].
 *
 */
declare class LightmapGIData extends Resource {
  /**
   * [LightmapGIData] contains baked lightmap and dynamic object probe data for [LightmapGI]. It is replaced every time lightmaps are baked in [LightmapGI].
   *
   */
  new(): LightmapGIData
  constructor()
  static new(): LightmapGIData

  /** The lightmap atlas texture generated by the lightmapper. */
  light_texture: TextureLayered

  /** The lightmap atlas textures generated by the lightmapper. */
  lightmap_textures: TextureLayered[]

  /** The shadowmask atlas textures generated by the lightmapper. */
  shadowmask_textures: TextureLayered[]

  /** Adds an object that is considered baked within this [LightmapGIData]. */
  add_user(
    path: NodePathType,
    uv_scale: Rect2,
    slice_index: int,
    sub_instance: int
  ): void

  /** Clear all objects that are considered baked within this [LightmapGIData]. */
  clear_users(): void

  /** Returns the number of objects that are considered baked within this [LightmapGIData]. */
  get_user_count(): int

  /** Returns the [NodePath] of the baked object at index [param user_idx]. */
  get_user_path(user_idx: int): NodePathType

  /** If [code]true[/code], lightmaps were baked with directional information. See also [member LightmapGI.directional]. */
  is_using_spherical_harmonics(): boolean

  /**
   * If [param uses_spherical_harmonics] is `true`, tells the engine to treat the lightmap data as if it was baked with directional information.
   *
   * **Note:** Changing this value on already baked lightmaps will not cause them to be baked again. This means the material appearance will look incorrect until lightmaps are baked again, in which case the value set here is discarded as the entire [LightmapGIData] resource is replaced by the lightmapper.
   *
   */
  set_uses_spherical_harmonics(uses_spherical_harmonics: boolean): void

  connect<T extends SignalsOf<LightmapGIData>>(
    signal: T,
    method: SignalFunction<LightmapGIData[T]>
  ): number

  /**
   * Shadowmasking is disabled. No shadowmask texture will be created when baking lightmaps. Existing shadowmask textures will be removed during baking.
   *
   */
  static SHADOWMASK_MODE_NONE: any

  /**
   * Shadowmasking is enabled. Directional shadows that are outside the [member DirectionalLight3D.directional_shadow_max_distance] will be rendered using the shadowmask texture. Shadows that are inside the range will be rendered using real-time shadows exclusively. This mode allows for more precise real-time shadows up close, without the potential "smearing" effect that can occur when using lightmaps with a high texel size. The downside is that when the camera moves fast, the transition between the real-time light and shadowmask can be obvious. Also, objects that only have shadows baked in the shadowmask (and no real-time shadows) won't display any shadows up close.
   *
   */
  static SHADOWMASK_MODE_REPLACE: any

  /**
   * Shadowmasking is enabled. Directional shadows will be rendered with real-time shadows overlaid on top of the shadowmask texture. This mode makes for smoother shadow transitions when the camera moves fast, at the cost of a potential smearing effect for directional shadows that are up close (due to the real-time shadow being mixed with a low-resolution shadowmask). Objects that only have shadows baked in the shadowmask (and no real-time shadows) will keep their shadows up close.
   *
   */
  static SHADOWMASK_MODE_OVERLAY: any
}
